"""update verse rec

Revision ID: 533fe32fe0e4
Revises: b8b8a62db1e8
Create Date: 2025-02-23 16:13:06.538977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '533fe32fe0e4'
down_revision: Union[str, None] = 'b8b8a62db1e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prayer_verse_recommendations', sa.Column('book_name', sa.String(), nullable=False))
    op.add_column('prayer_verse_recommendations', sa.Column('chapter_number', sa.Integer(), nullable=False))
    op.add_column('prayer_verse_recommendations', sa.Column('verse_number_start', sa.Integer(), nullable=False))
    op.add_column('prayer_verse_recommendations', sa.Column('verse_number_end', sa.Integer(), nullable=True))
    op.drop_column('prayer_verse_recommendations', 'verse_reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prayer_verse_recommendations', sa.Column('verse_reference', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('prayer_verse_recommendations', 'verse_number_end')
    op.drop_column('prayer_verse_recommendations', 'verse_number_start')
    op.drop_column('prayer_verse_recommendations', 'chapter_number')
    op.drop_column('prayer_verse_recommendations', 'book_name')
    # ### end Alembic commands ###
