"""added prayer verse recommendation

Revision ID: b8b8a62db1e8
Revises: ac0e3bfc156c
Create Date: 2025-02-23 16:01:05.010545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b8a62db1e8'
down_revision: Union[str, None] = 'ac0e3bfc156c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
