"""update verse to encouragement

Revision ID: fe3e4b008e08
Revises: 533fe32fe0e4
Create Date: 2025-02-23 23:12:05.555996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe3e4b008e08'
down_revision: Union[str, None] = '533fe32fe0e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prayer_verse_recommendations', sa.Column('encouragement', sa.Text(), nullable=False))
    op.drop_column('prayer_verse_recommendations', 'justification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prayer_verse_recommendations', sa.Column('justification', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('prayer_verse_recommendations', 'encouragement')
    # ### end Alembic commands ###
